server:
  port: 60000
spring:
  resources:
    static-locations: classpath:/static/,classpath:/views/,file:${web.upload},file:${web.ueditorUpload}
  datasource:
    url: jdbc:sqlite::resource:static/sqlite3/mrm.db
  jpa:
    database-platform: indi.likai.mrm.utils.SQLiteDialect
    hibernate:
      ddl-auto: update

    show-sql: true
